### ISSUE TITLE
Problem with the dateTime variable

### ISSUE THREAD

**Issue by neocotic** [template-extension/template-chrome#222]
A user has raised the following ticket:

> I've created a template to copy text and then create the text for a footnote in documents I'm writing. 
the text is: 
>“{selection}” {author}, {title}, {host}, {url} (accessed {dateTime}).
>
>But no matter where I test it I'm unable to get anything to the clipboard. At the most I'm getting a progress meter (sometimes) by the template icon in the toolbar, but it never progresses to more than 50% otherwise it just sits there doing nothing at all.
>
> What am I doing wrong?

They then provided some additional information which indicates that there's a problem with the `dateTime` variable.

This can be (and has been) verified by creating a simple template that outputs only `{dateTime}` and it will fail to complete.

**Comment by tcblack** [comment]
I was able to work around it by setting it as a segment (?)
"{selection}" 
{author}, {title}, {host}, {url} (Accessed  {#dateTime}m/d/Y{/dateTime}).

**Comment by neocotic** [comment]
Thanks @tcblack, that's good to know. I'll continue to try and work out why the standard variable is not rendering the current date/time in [RFC 2822](http://www.faqs.org/rfcs/rfc2822.html) format.

**Comment by neocotic** [comment]
@tcblack, you'll be happy to know that I've fixed the problem and published version 1.2.9. Unfortunately, Google review each update so it won't be available immediately.

Once you have the update, I'd appreciate it if you could test all of your templates to make sure that nothing else was affected as a result of this fix.

**Comment by tcblack** [comment]
You'll be happy to know that I have not found any other problems.  Thank you.
